<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUBxFhTG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUBxFhTG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUBxFhTG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUBxFhTG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUBxFhTG\App_KernelDevDebugContainer([
    'container.build_hash' => 'UBxFhTG',
    'container.build_id' => '5959e37d',
    'container.build_time' => 1678884347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUBxFhTG');
