<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'dashboard_user_rapport' => [[], ['_controller' => 'App\\Controller\\RapportController::dashboard_user'], [], [['text', '/all_rapport_admin']], [], [], []],
    'dashboard_user_rapports' => [[], ['_controller' => 'App\\Controller\\RapportController::dashboard_user_rapport'], [], [['text', '/all_rapport_admins']], [], [], []],
    'dashboard_user_rapports_show' => [['id'], ['_controller' => 'App\\Controller\\RapportController::dashboard_user_rapport_print'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/all_rapport_admin_show']], [], [], []],
    'rapport_rapport_user' => [[], ['_controller' => 'App\\Controller\\RapportController::recent_rapport'], [], [['text', '/recent/rapport']], [], [], []],
    'find_user_rapport' => [['id'], ['_controller' => 'App\\Controller\\RapportController::findRapport'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/find/rapport']], [], [], []],
    'create_rapport' => [[], ['_controller' => 'App\\Controller\\RapportController::insertUser'], [], [['text', '/api/rapport/add']], [], [], []],
    'rapports_update' => [['id'], ['_controller' => 'App\\Controller\\RapportController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/rapport/edit']], [], [], []],
    'rapports_delete' => [['id'], ['_controller' => 'App\\Controller\\RapportController::deleteRapport'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/rapport/delete']], [], [], []],
    'rapports_delete_admin' => [['id'], ['_controller' => 'App\\Controller\\RapportController::deleteRapportAdmin'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/rapport/delete/admin']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::logout'], [], [['text', '/logout']], [], [], []],
    'app_project' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::index'], [], [['text', '/admin']], [], [], []],
    'gestion/users' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::dashboard_user'], [], [['text', '/all/users']], [], [], []],
    'app_utilisateur' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::insertUser'], [], [['text', '/user/add']], [], [], []],
    'app_utilisateur_delete' => [['id'], ['_controller' => 'App\\Controller\\UtilisateurController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
